version: '3.7'

services:
  puppeteer:
    build: puppeteer
    image: puppeteer-chrome-linux
    init: true
    cap_add:
      - SYS_ADMIN
    container_name: puppeteer-chrome
    tty: true
    stdin_open: true
    volumes:
      - ./puppeteer/app:/app
    working_dir: /app
    depends_on: [db]
  db:
    image: mysql:5.7
    container_name: scraping_db
    restart: always
    environment: 
      MYSQL_DATABASE: test_db
      MYSQL_USER: puppeteer
      MYSQL_PASSWORD: puppeteer
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    ports: 
      - "3306:3306"
    volumes: 
      - ./db:/data/db
      - ./configdb:/data/configdb